# BEGIN
---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  config:
    activate:
      on-profile: development
  datasource:
    password: 123
    url: jdbc:h2:mem:test
    username: sa
# END
